# Ansible Playbook for Subutai's Readthedocs
---

- hosts: all
  gather_facts: false
  remote_user: root
  tasks:

    - name: Update
      raw: apt-get -y --allow-unauthenticated update || true

    - name: Ensure python is available
      raw: test -e /usr/bin/python || apt install -y --allow-unauthenticated python-minimal

    - name: Ensure python-apt is available
      raw: test -d /usr/share/python-apt || apt install -y --allow-unauthenticated python-apt

    - name: Upgrade
      raw: apt-get -y --allow-unauthenticated upgrade
    
- hosts: rtd
  remote_user: root
  tasks:

    - name: Install extra packages
      apt:
        name: "{{ item }}"
      with_items:
        - git
        - python3-pip
        - virtualenv
        - python3-venv
        - pandoc

    - name: Install Sphinx and RTD Theme
      pip:
        name: "{{ item }}"
      with_items:
        - sphinx
        - sphinx-autobuild
        - recommonmark
        - sphinx_rtd_theme
    
    - name: Create Virtual Env Dir
      file:
          path: /srv/rtd
          state: directory

    - name: Create Virtual Env
      command: virtualenv /srv/rtd creates="/srv/rtd/rtd_env"

    - name: Install RTD
      git: 
        repo: https://github.com/rtfd/readthedocs.org.git 
        dest: /srv/rtd/source

    - name: Install requirements from pip
      pip:
        virtualenv: /srv/rtd/rtd_env
        requirements: /srv/rtd/source/requirements/pip.txt

    - name: Install flup 
      pip:
        name: flup
        virtualenv: /srv/rtd/rtd_env

    - name: RTD Server migrate
      django_manage:
          app_path: /srv/rtd/source
          virtualenv: /srv/rtd/rtd_env
          command: migrate

    - name: RTD generate the static assets
      django_manage:
          app_path: /srv/rtd/source
          virtualenv: /srv/rtd/rtd_env
          command: collectstatic

    - name: Create Django super user
      shell:
          . ../rtd_env/bin/activate && echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin', '{{ user_email }}', '{{ user_password }}')" | python manage.py shell
      args:
          chdir: /srv/rtd/source

    - name: Install uWSGI
      pip:
          name: uwsgi
          virtualenv: /srv/rtd/rtd_env

    - name: Configure Rtd ini file 
      copy:
          src:  uwsgi/rtd.ini
          dest: /srv/rtd/source/readthedocs/rtd.ini
          owner: root
          group: root


    - name: RTD uWSGI Server Up 
      shell: . ../rtd_env/bin/activate && uwsgi --ini readthedocs/rtd.ini
      args:
          chdir: /srv/rtd/source
